language: generic

sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - secure: "djh48ifdDOLzCJ6Su64GEd8IxpK1l39mbu9e2EjVNhhihtusRx4MRPJffwUjxp3qE0bcUSXVfHksbl5O2ZKboV1sbMwXTPZ2qeJlwvaLEVtp7soZaG+YjdKWB7x8vIlIijHhuOGS8R4MXf5AtKuOcHK7wxKxUp4NSCR8AqG4gafmrN5CuEgQJAQSpyXy4/8XQFC5+psaxskXWofKUyjFSkZxdl0aztXXbUoOIpG5c00td2+0lGQWqavGgkHxbiTjYqdmuVeCvR+K4i/xvcUaVFKVJ150FCL7ydYOf7pa3MOekg0zQ0Q7uJmvpyVGcrwcTlLXOMEHAh+euw35KBDgPkoE6jhOUaJ3CaZBQQ87aUBU+QVWSLWUdXxH/wXULJ4XLhFkOBvIwakfl+/yb7rm7u0+tHgxdvLWojR4Jf6yBVv8rYvMJsxauxf0zqVVjWB0KFLX/alZ0vwR6W8+qKItVxR5DDj9XQesnSlNJNj9YE+YZqcy6tLGxKL7yLJ4Ef8DoX5OY+/I+Q0Q1BAC2OEfbbnpdY4CYCZEeI5u76k6LrO3lsRbv0W/1rjIiiAjyGBmuWIWdI7PMD1U+JbqTRqzRScU/NWvE/JM5A8xr4MOPS6xv4kVMwI8gVTI4Lgbdy4vXLn0cYOs2Y924iGpic/b8N0tdobh4SJiUKMis2Xh6ck="

addons:
  apt:
    packages:
    - gettext
    - libunwind8
    - libicu52

before_install:
  - curl -sSL -o dotnet.tar.gz https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-linux-x64.tar.gz
  - sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
  - sudo ln -s /opt/dotnet/dotnet /usr/local/bin

script:
  - pushd test/Tmds.Fuse.Tests && dotnet restore && dotnet test && popd
  - VERSION_SUFFIX="$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER"
  - dotnet pack src/Tmds.Fuse --configuration Release --version-suffix $VERSION_SUFFIX --output .

after_success:
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.Fuse/Tmds.Fuse.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
     fi'
